### ISSUE TITLE
Named Tables to DataTable?

### ISSUE THREAD

**Issue by sanzoghenzo** [smartquant/ExcelDna.Utilities#2]
Hi @smartquant, thanks for this library!
I'm moving from Excel VBA to C# and I find your work really helpful to hel me transition.
For my previous VBA projects I used extensively Excel named tables, and I could quickly retrieve them with `range("tablename")` for the data cells and `range("tablename[#All]")` for the entire table (including headers).
It seems that I cannot do this with ExcelDna.Utilities. Is that right or am I missing something?
If it cannot be done right now, could it be possible to add such feature?
Thanks in advance

**Comment by smartquant** [comment]
Hi @sanzoghenzo ,

This functionality is already included in the extension method ExcelReferenceEx.ToDataTable
Just do the following:

```
        var ws = Worksheet.ActiveSheet();
        var dt1 = ws.Range("table1").ToDataTable(header: false);
        var dt2 = ws.Range("table1[#All]").ToDataTable(header: true);
```

**Comment by sanzoghenzo** [comment]
thanks @smartquant, I found the real problem: I'm an italian user and I need to use the localized keyword "#Tutti" instead of "#All".
In VBA I had to use the english version, so I (wrongly) took granted the same behavior in exceldna.
This will cause portability problems, since I'm developing some plugins for an international company :(
Thanks again!
